# Generated by Django 2.1.7 on 2019-04-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_link', models.TextField()),
                ('thread_name', models.CharField(max_length=200)),
                ('head_line', models.CharField(max_length=200)),
                ('by', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('additional_text', models.TextField()),
                ('img_path', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField(blank=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Please Input a valid Email address', max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
